<!--
  The motion control: the SCREEN switch's purpose, re-homed (plan 13-04,
  13-CONTEXT.md D-09; Bible §14 "stop ambient preview loops" and "keep motion
  generated by instrument output controllable").

  ONE CHECKBOX, NOT A SEGMENTED SWITCH. There are no longer four layers to
  choose between; there is one question - do the previews move on their own -
  and a checkbox is the honest shape of one question. Checked means still.

  WHAT IT STOPS AND WHAT IT LEAVES ALONE. The shared simulator host stills
  every ambient preview when the preference says still, and under that flag a
  pad animates only while a finger is on it (src/lib/sim/host.ts, active()).
  That is §6's "animate only the selected or explicitly previewed card" read
  as a user control: the wall holds one frame per card, the pad under your
  finger still answers.

  ADDITIVE TO prefers-reduced-motion, NEVER SUBTRACTIVE. When the operating
  system already asks for less motion the box is shown checked and disabled:
  the previews are already still, and a control that offered to start them
  would be offering something it cannot deliver (src/lib/sim/motion.svelte.ts
  reports `os || still` and has no branch that turns the OS's true into
  false). The explanation says the rule in one clause so the disabled state
  is plain rather than coy (D-05).

  WHERE IT LIVES. The PDF draws `Help & shortcuts · Device actions` in the
  footer of every shell page; this control belongs under Help & shortcuts.
  13-05 builds that footer and the link; until then this is a self-contained
  block mounted in the existing layout footer, and 13-05 moves it without
  changing it. 13-06 folds the storage key into the store module.

  THE STRINGS ARE THE MODULE'S, not this file's, so 13-18 reads them from one
  place; both are ledgered in 13-COPY-NEW.md.

  Copyright (C) 2026 Botond Sandor. Licensed under the GNU GPL v3 or later.
-->
<script lang="ts">
  import { onMount } from "svelte";
  import {
    chooseMotion,
    motion,
    MOTION_EXPLANATION,
    MOTION_LABEL,
    osQuery,
  } from "$lib/sim/motion.svelte";

  const EXPLANATION_ID = "motion-explanation";

  /**
   * The OS half, held as state so the box can follow a mid-session toggle.
   * Read in onMount because matchMedia does not exist in the prerenderer.
   */
  let osReduced = $state(false);
  onMount(() => {
    const query = osQuery();
    if (query === undefined) return;
    const sync = (): void => {
      osReduced = query.matches;
    };
    sync();
    query.addEventListener("change", sync);
    return () => query.removeEventListener("change", sync);
  });

  const still = $derived(osReduced || motion.choice === "still");
</script>

<div class="motion" data-testid="motion-control">
  <label class="row">
    <input
      type="checkbox"
      data-testid="motion-still"
      checked={still}
      disabled={osReduced}
      aria-describedby={EXPLANATION_ID}
      onchange={(event) =>
        chooseMotion(event.currentTarget.checked ? "still" : "animated")}
    />
    <span class="label">{MOTION_LABEL}</span>
  </label>
  <p class="explanation" id={EXPLANATION_ID}>{MOTION_EXPLANATION}</p>
</div>

<style>
  /* Its own line in the footer's wrapping row: a sentence beside four links
     would read as a fifth link. */
  .motion {
    flex-basis: 100%;
  }

  /* The label is the touch target, 44px on the block axis (§14). */
  .row {
    display: flex;
    align-items: center;
    gap: 8px;
    min-block-size: 44px;
    cursor: pointer;
  }

  .row:has(input:disabled) {
    cursor: default;
  }

  input {
    inline-size: 16px;
    block-size: 16px;
    margin: 0;
    accent-color: var(--color-action);
  }

  .label {
    font-family: var(--font-sans);
    font-size: 13px;
    line-height: 1.45;
    color: var(--color-ink);
  }

  .explanation {
    margin: 0;
    max-inline-size: 60ch;
    font-family: var(--font-sans);
    font-size: 13px;
    line-height: 1.45;
    color: var(--color-ink-quiet);
  }
</style>
