// The ambient-motion preference: the SCREEN switch's one surviving purpose,
// re-homed by plan 13-04 (13-CONTEXT.md D-09, 2026-09-11).
//
// WHAT SURVIVED THE TEXTURE. The SCREEN switch turned four CRT layers off; the
// layers are gone (D-09) and the switch with them. Its purpose is not: the
// Bible's §14 asks to "respect reduced motion; stop ambient preview loops"
// and to "keep motion generated by instrument output controllable", and §6
// says "animate only the selected or explicitly previewed card". A visitor
// whose operating system does not ask for less motion, but who does not want
// thirty pads moving while they read, needs a control the OS does not give
// them. This module is that control's state; MotionControl.svelte is its
// face, mounted in the footer under Help & shortcuts (13-05 builds the footer
// that carries the link; the control lands first so the purpose is never
// homeless).
//
// ADDITIVE TO prefers-reduced-motion, NEVER SUBTRACTIVE - AND THE SHAPE OF
// THE CODE IS WHAT MAKES THAT A RULE RATHER THAN A PROMISE. src/lib/sim/host.ts
// stills every engine when its `reducedMotion` dependency reports true, and
// under that flag a pad animates only while a finger is on it (host.ts's
// active(): "the user causing the motion is the carve-out; uninvited ambient
// motion is not"). motionDeps() below is that dependency, and the value it
// reports is `os || still`: the operating system's media query OR this
// preference. A visitor whose OS asks for less motion cannot be given motion
// by this control, because there is no branch in which the OS's true becomes
// false. host.ts is read and not edited (13-04); the host takes its
// dependencies through its constructor precisely so a source like this one
// can be injected without a change to the loop.
//
// THE KEY, THE TWO WORDS AND THE GUARD LIVE IN src/lib/store/ SINCE 13-06.
// 13-04 wrote them here with ScreenToggle.svelte's guard copied line for
// line; 13-06 folded the key into schema.ts beside the KEEP-* keys and the
// read and the write into store/motion.ts over store/local.ts, so a browser
// configured to refuse storage - which can throw on the PROPERTY ACCESS and
// not only on use (07-RESEARCH pitfall 9) - is handled in one place for
// every store. What stays here is what needs the browser: storage() reads
// the global inside a try of its own and hands it in, because the store
// modules take the store as an argument and never name it. The stored value
// is the same bare word it was (`animated` / `still`, never JSON), the
// default is the same, and the additive rule below is unchanged; the tagged
// reduced-motion title in e2e/browse.e2e.ts writes the key by hand and is
// the proof the fold moved nothing.
//
// READ ONCE AT MODULE SCOPE, NEVER SUBSCRIBED TO. The recorded choice is
// picked up before hydration so a visitor who chose still never watches the
// wall start moving and stop. The OS half IS subscribed to, inside
// motionDeps(), because an operating-system toggle mid-session must take
// effect without a remount (IDENT-02) - and that subscription is the host's
// own contract, carried here unchanged.
//
// Copyright (C) 2026 Botond Sandor. Licensed under the GNU GPL v3 or later.
import {
  MOTION_CHOICES,
  MOTION_KEY,
  readMotion,
  writeMotion,
  type MotionChoice,
} from "../store/motion";
import type { HostDeps } from "./host";

// Re-exported so the names 13-04 published still resolve from here.
export { MOTION_CHOICES, MOTION_KEY };
export type { MotionChoice };

/**
 * The control's two strings, in D-05's register and ledgered in
 * 13-COPY-NEW.md for 13-18. Real apostrophes, no exclamation marks, sentence
 * case: the label names the action and the explanation names the result and
 * the rule.
 */
export const MOTION_LABEL = "Keep previews still";
export const MOTION_EXPLANATION =
  "Cards hold one frame instead of animating. A pad still answers your finger, and your system’s reduced-motion setting always wins.";

/**
 * The store, or undefined. The property ACCESS of the global is inside the
 * try, not just the call: 07-RESEARCH pitfall 9. This is the only line in
 * the motion path that names the browser store; the store modules take it
 * as an argument.
 */
function storage(): Storage | undefined {
  try {
    return typeof localStorage === "undefined" ? undefined : localStorage;
  } catch {
    return undefined;
  }
}

/** The recorded choice, or undefined for anything that is not one of the two. */
const recorded = (): MotionChoice | undefined => readMotion(storage());

/** Never throws. A preference that could not be written is still the live preference. */
const remember = (choice: MotionChoice): void => {
  writeMotion(storage(), choice);
};

/**
 * The live choice, shared. `const` and a property rather than an exported
 * `let`: reassigning an exported binding from another module is not something
 * Svelte can track.
 */
export const motion = $state<{ choice: MotionChoice }>({ choice: "animated" });

if (typeof document !== "undefined") {
  motion.choice = recorded() ?? "animated";
}

/**
 * Every injected host dependency listening for the preference to move. A
 * plain array and not a Set or a rune: it holds callbacks, nothing renders
 * it, and svelte/prefer-svelte-reactivity would otherwise ask for a SvelteSet
 * that this has no reason to be.
 */
const listeners: Array<() => void> = [];

export function chooseMotion(choice: MotionChoice): void {
  motion.choice = choice;
  remember(choice);
  for (const notify of [...listeners]) notify();
}

/**
 * The operating system's own answer, read live. Exported so the control can
 * show itself checked and disabled when the OS has already decided, rather
 * than offering a choice that cannot take effect.
 */
export function osQuery(): MediaQueryList | undefined {
  if (typeof window === "undefined") return undefined;
  if (typeof window.matchMedia !== "function") return undefined;
  return window.matchMedia("(prefers-reduced-motion: reduce)");
}

/**
 * The host's `reducedMotion` dependency with this preference folded in.
 *
 * `os || still`, and nothing else. The OS query is subscribed to exactly as
 * the host's own default does it; the preference is subscribed to through
 * chooseMotion(). Either changing re-reports the OR, and host.ts ignores a
 * report that did not change its value. stop() removes both.
 */
export function motionDeps(): Pick<HostDeps, "reducedMotion"> {
  return {
    reducedMotion: (cb) => {
      const query = osQuery();
      const current = (): boolean =>
        (query?.matches ?? false) || motion.choice === "still";
      const notify = (): void => cb(current());
      query?.addEventListener("change", notify);
      listeners.push(notify);
      return {
        matches: current(),
        stop: () => {
          query?.removeEventListener("change", notify);
          const at = listeners.indexOf(notify);
          if (at >= 0) listeners.splice(at, 1);
        },
      };
    },
  };
}
